export interface LocationEntry {
  term: string;          // string to match in text (case-insensitive, whole-word)
  canonical: string;     // full canonical name shown in tooltip
  type:
    | "hospital"
    | "restaurant"
    | "mall"
    | "airport"
    | "station"
    | "district"
    | "street"
    | "immigration"
    | "consulate"
    | "attraction"
    | "terminal"
    | "city"
    | "exchange"
    | "store"
    | "other";
  category_ru: string;   // user-facing type in Russian
  mapsQuery: string;     // query string for Google Maps URL
  aliases?: string[];    // alternate spellings / Cyrillic forms
}

export const LOCATIONS: LocationEntry[] = [
  // ── Hospitals ──────────────────────────────────────────────────────────────
  {
    term: "Bumrungrad",
    canonical: "Bumrungrad International Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Bumrungrad International Hospital Bangkok",
    aliases: ["Бумрунград"],
  },
  {
    term: "Samitivej",
    canonical: "Samitivej Hospital Sukhumvit",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Samitivej Hospital Sukhumvit Bangkok",
    aliases: ["Самитведж"],
  },
  {
    term: "Bangkok Hospital",
    canonical: "Bangkok Hospital (Main)",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Bangkok Hospital New Petchburi Road Bangkok",
    aliases: ["Bangkok Dusit Medical"],
  },
  {
    term: "BNH Hospital",
    canonical: "BNH Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "BNH Hospital Convent Road Silom Bangkok",
    aliases: ["BNH"],
  },
  {
    term: "MedPark",
    canonical: "MedPark Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "MedPark Hospital Rama IV Road Bangkok",
    aliases: ["Медпарк"],
  },
  {
    term: "Bangkok Christian Hospital",
    canonical: "Bangkok Christian Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Bangkok Christian Hospital Silom Road Bangkok",
    aliases: ["Christian Hospital", "Кристьян госпиталь"],
  },
  {
    term: "BCare Medical Center",
    canonical: "BCare Medical Center",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "BCare Medical Center Phahonyothin Bangkok",
    aliases: ["BCare"],
  },
  {
    term: "Vejthani Hospital",
    canonical: "Vejthani Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Vejthani Hospital Bangkok",
    aliases: ["Vejthani"],
  },
  {
    term: "Praram 9 Hospital",
    canonical: "Praram 9 Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Praram 9 Hospital Rama IX Road Bangkok",
    aliases: ["Phra Ram 9 Hospital", "Praram9"],
  },
  {
    term: "Manarom Hospital",
    canonical: "Manarom Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Manarom Hospital Bangkok",
  },
  {
    term: "Lad Phrao Hospital",
    canonical: "Lad Phrao Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Lad Phrao Hospital Bangkok",
  },
  {
    term: "Thantakit International Dental Center",
    canonical: "Thantakit International Dental Center",
    type: "hospital",
    category_ru: "Стоматология",
    mapsQuery: "Thantakit International Dental Center New Petchaburi Bangkok",
    aliases: ["Thantakit"],
  },
  {
    term: "Truth Dental",
    canonical: "Truth Dental Clinic",
    type: "hospital",
    category_ru: "Стоматология",
    mapsQuery: "Truth Dental Clinic Chit Lom Bangkok",
  },
  {
    term: "Chulalongkorn University Dental Hospital",
    canonical: "Chulalongkorn University Dental Hospital",
    type: "hospital",
    category_ru: "Стоматология",
    mapsQuery: "Chulalongkorn University Dental Hospital Henri Dunant Bangkok",
    aliases: ["CU Dental"],
  },
  {
    term: "Samitivej Srinakarin",
    canonical: "Samitivej Srinakarin Hospital",
    type: "hospital",
    category_ru: "Больница",
    mapsQuery: "Samitivej Srinakarin Hospital Bangkok",
  },

  // ── Airports ───────────────────────────────────────────────────────────────
  {
    term: "Suvarnabhumi",
    canonical: "Suvarnabhumi Airport (BKK)",
    type: "airport",
    category_ru: "Аэропорт",
    mapsQuery: "Suvarnabhumi Airport Bangkok",
    aliases: ["Суварнабхуми", "Суварна", "BKK airport"],
  },
  {
    term: "Don Mueang",
    canonical: "Don Mueang International Airport (DMK)",
    type: "airport",
    category_ru: "Аэропорт",
    mapsQuery: "Don Mueang International Airport Bangkok",
    aliases: ["Don Muang", "Дон Муанг", "Дон Мыанг", "DMK"],
  },

  // ── Airport Rail Link ──────────────────────────────────────────────────────
  {
    term: "Airport Rail Link",
    canonical: "Airport Rail Link (Suvarnabhumi City Line)",
    type: "station",
    category_ru: "Аэроэкспресс",
    mapsQuery: "Airport Rail Link Bangkok Suvarnabhumi",
    aliases: ["ARL", "Airport Link"],
  },

  // ── BTS Stations ───────────────────────────────────────────────────────────
  {
    term: "BTS Ekkamai",
    canonical: "BTS Ekkamai Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Ekkamai Station Bangkok",
    aliases: ["BTS Эккамай"],
  },
  {
    term: "BTS Asok",
    canonical: "BTS Asok Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Asok Station Bangkok",
  },
  {
    term: "BTS Phrom Phong",
    canonical: "BTS Phrom Phong Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Phrom Phong Station Bangkok",
  },
  {
    term: "BTS Thonglor",
    canonical: "BTS Thonglor Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Thonglor Station Bangkok",
  },
  {
    term: "BTS Siam",
    canonical: "BTS Siam Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Siam Station Bangkok",
  },
  {
    term: "BTS Chit Lom",
    canonical: "BTS Chit Lom Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Chit Lom Station Bangkok",
  },
  {
    term: "BTS Saphan Taksin",
    canonical: "BTS Saphan Taksin Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Saphan Taksin Station Bangkok",
  },
  {
    term: "BTS Nana",
    canonical: "BTS Nana Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Nana Station Bangkok",
  },
  {
    term: "BTS On Nut",
    canonical: "BTS On Nut Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS On Nut Station Bangkok",
  },
  {
    term: "BTS National Stadium",
    canonical: "BTS National Stadium Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS National Stadium Station Bangkok",
  },
  {
    term: "BTS Mo Chit",
    canonical: "BTS Mo Chit Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Mo Chit Station Bangkok",
  },
  {
    term: "BTS Punnawithi",
    canonical: "BTS Punnawithi Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Punnawithi Station Bangkok",
  },
  {
    term: "BTS Phaya Thai",
    canonical: "BTS Phaya Thai Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Phaya Thai Station Bangkok",
  },
  {
    term: "BTS Victory Monument",
    canonical: "BTS Victory Monument Station",
    type: "station",
    category_ru: "Станция BTS",
    mapsQuery: "BTS Victory Monument Station Bangkok",
  },

  // ── MRT Stations ───────────────────────────────────────────────────────────
  {
    term: "MRT Chatuchak Park",
    canonical: "MRT Chatuchak Park Station",
    type: "station",
    category_ru: "Станция MRT",
    mapsQuery: "MRT Chatuchak Park Station Bangkok",
  },
  {
    term: "MRT Phetchaburi",
    canonical: "MRT Phetchaburi Station",
    type: "station",
    category_ru: "Станция MRT",
    mapsQuery: "MRT Phetchaburi Station Bangkok",
  },
  {
    term: "MRT Lumpini",
    canonical: "MRT Lumpini Station",
    type: "station",
    category_ru: "Станция MRT",
    mapsQuery: "MRT Lumpini Station Bangkok",
  },
  {
    term: "Krung Thep Aphiwat",
    canonical: "Krung Thep Aphiwat Central Terminal (Bang Sue Grand Station)",
    type: "station",
    category_ru: "Вокзал / Станция MRT",
    mapsQuery: "Krung Thep Aphiwat Central Terminal Bangkok",
    aliases: ["Bang Sue Grand Station", "Bang Sue"],
  },

  // ── Districts / Neighborhoods ──────────────────────────────────────────────
  {
    term: "Sukhumvit",
    canonical: "Sukhumvit (district / road)",
    type: "district",
    category_ru: "Район / улица",
    mapsQuery: "Sukhumvit Road Bangkok",
    aliases: ["Сукхумвит"],
  },
  {
    term: "Thonglor",
    canonical: "Thonglor (Sukhumvit Soi 55)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Thonglor Sukhumvit Soi 55 Bangkok",
    aliases: ["Тонглор"],
  },
  {
    term: "Ekkamai",
    canonical: "Ekkamai (Sukhumvit Soi 63)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Ekkamai Sukhumvit Soi 63 Bangkok",
    aliases: ["Эккамай", "Экхамай"],
  },
  {
    term: "Phrom Phong",
    canonical: "Phrom Phong (Sukhumvit Soi 37–39 area)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Phrom Phong Bangkok Sukhumvit",
    aliases: ["Пром Понг"],
  },
  {
    term: "Asok",
    canonical: "Asok (Sukhumvit Soi 21)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Asok Sukhumvit Bangkok",
    aliases: ["Асок"],
  },
  {
    term: "Silom",
    canonical: "Silom (district / road)",
    type: "district",
    category_ru: "Район / улица",
    mapsQuery: "Silom Road Bangkok",
    aliases: ["Силом"],
  },
  {
    term: "Sathorn",
    canonical: "Sathorn (district)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Sathorn Bangkok",
    aliases: ["Сатхорн"],
  },
  {
    term: "On Nut",
    canonical: "On Nut (Sukhumvit Soi 77)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "On Nut Bangkok",
    aliases: ["Он Нут"],
  },
  {
    term: "Nana",
    canonical: "Nana (Sukhumvit Soi 3 area)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Nana Bangkok Sukhumvit",
    aliases: ["Нана"],
  },
  {
    term: "Ari",
    canonical: "Ari (district)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Ari Bangkok",
    aliases: ["Ари"],
  },
  {
    term: "Ratchada",
    canonical: "Ratchadaphisek (district / road)",
    type: "district",
    category_ru: "Район / улица",
    mapsQuery: "Ratchadaphisek Road Bangkok",
    aliases: ["Ratchadaphisek", "Рачада"],
  },
  {
    term: "Khao San",
    canonical: "Khao San Road",
    type: "street",
    category_ru: "Улица / район",
    mapsQuery: "Khao San Road Bangkok",
    aliases: ["Khaosan Road", "Khaosan", "Каосан", "Каосан-роад"],
  },
  {
    term: "Yaowarat",
    canonical: "Yaowarat Road (Chinatown Bangkok)",
    type: "district",
    category_ru: "Чайнатаун / улица",
    mapsQuery: "Yaowarat Road Chinatown Bangkok",
    aliases: ["Яоварат", "Chinatown Bangkok"],
  },
  {
    term: "Rattanakosin",
    canonical: "Rattanakosin Island (Old Town Bangkok)",
    type: "district",
    category_ru: "Старый город",
    mapsQuery: "Rattanakosin Island Bangkok",
    aliases: ["Rattanakoshin", "Раттанакосин"],
  },
  {
    term: "Pratunam",
    canonical: "Pratunam (district / market area)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Pratunam Bangkok",
    aliases: ["Prathunam", "Пратунам"],
  },
  {
    term: "Patpong",
    canonical: "Patpong (Silom nightlife area)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Patpong Bangkok Silom",
    aliases: ["Патпонг"],
  },
  {
    term: "Huai Khwang",
    canonical: "Huai Khwang (district)",
    type: "district",
    category_ru: "Район",
    mapsQuery: "Huai Khwang Bangkok",
    aliases: ["Хуай Кхуанг"],
  },

  // ── Specific Streets / Sois ────────────────────────────────────────────────
  {
    term: "Sukhumvit Soi 11",
    canonical: "Sukhumvit Soi 11",
    type: "street",
    category_ru: "Улица",
    mapsQuery: "Sukhumvit Soi 11 Bangkok",
  },
  {
    term: "Sukhumvit Soi 40",
    canonical: "Sukhumvit Soi 40",
    type: "street",
    category_ru: "Улица",
    mapsQuery: "Sukhumvit Soi 40 Bangkok",
  },
  {
    term: "Silom Soi 4",
    canonical: "Silom Soi 4",
    type: "street",
    category_ru: "Улица",
    mapsQuery: "Silom Soi 4 Bangkok",
  },

  // ── Shopping Malls ─────────────────────────────────────────────────────────
  {
    term: "Terminal 21",
    canonical: "Terminal 21 Asok",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "Terminal 21 Asok Bangkok",
    aliases: ["Terminal 21 Asok", "Терминал 21"],
  },
  {
    term: "Siam Paragon",
    canonical: "Siam Paragon",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "Siam Paragon Bangkok",
    aliases: ["Сиам Парагон"],
  },
  {
    term: "MBK",
    canonical: "MBK Center",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "MBK Center Bangkok",
    aliases: ["MBK Center"],
  },
  {
    term: "ICON SIAM",
    canonical: "ICON SIAM",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "ICON SIAM Bangkok",
    aliases: ["Icon Siam", "Айкон Сиам"],
  },
  {
    term: "Fortune Town",
    canonical: "Fortune Town (IT & electronics mall)",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "Fortune Town Bangkok",
    aliases: ["Форчун Таун"],
  },
  {
    term: "CentralWorld",
    canonical: "CentralWorld",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "CentralWorld Bangkok",
    aliases: ["Central World"],
  },
  {
    term: "Central Embassy",
    canonical: "Central Embassy",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "Central Embassy Bangkok",
  },
  {
    term: "Emsphere",
    canonical: "Emsphere",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "Emsphere Bangkok Phrom Phong",
  },
  {
    term: "EmQuartier",
    canonical: "EmQuartier",
    type: "mall",
    category_ru: "ТЦ",
    mapsQuery: "EmQuartier Bangkok Phrom Phong",
  },
  {
    term: "True Digital Park",
    canonical: "True Digital Park",
    type: "other",
    category_ru: "Коворкинг / Комплекс",
    mapsQuery: "True Digital Park Bangkok Punnawithi",
  },
  {
    term: "Asiatique",
    canonical: "Asiatique The Riverfront",
    type: "mall",
    category_ru: "Ночной рынок",
    mapsQuery: "Asiatique The Riverfront Bangkok",
  },

  // ── Markets ────────────────────────────────────────────────────────────────
  {
    term: "Chatuchak Market",
    canonical: "Chatuchak Weekend Market",
    type: "mall",
    category_ru: "Рынок",
    mapsQuery: "Chatuchak Weekend Market Bangkok",
    aliases: ["Chatuchak", "Чатучак", "JJ Market"],
  },
  {
    term: "Khlong Toei Market",
    canonical: "Khlong Toei Market",
    type: "mall",
    category_ru: "Рынок",
    mapsQuery: "Khlong Toei Market Bangkok",
    aliases: ["Klong Toey Market"],
  },
  {
    term: "Huai Khwang Market",
    canonical: "Huai Khwang Market",
    type: "mall",
    category_ru: "Рынок",
    mapsQuery: "Huai Khwang Market Bangkok",
  },
  {
    term: "Phra Khanong Market",
    canonical: "Phra Khanong Market",
    type: "mall",
    category_ru: "Рынок",
    mapsQuery: "Phra Khanong Market Bangkok",
  },

  // ── Supermarkets / Stores ──────────────────────────────────────────────────
  {
    term: "Villa Market",
    canonical: "Villa Market",
    type: "store",
    category_ru: "Супермаркет",
    mapsQuery: "Villa Market Bangkok",
    aliases: ["Вилла маркет"],
  },
  {
    term: "Foodland",
    canonical: "Foodland Supermarket",
    type: "store",
    category_ru: "Супермаркет",
    mapsQuery: "Foodland Supermarket Bangkok",
    aliases: ["Фудлэнд"],
  },
  {
    term: "Tops Market",
    canonical: "Tops Market",
    type: "store",
    category_ru: "Супермаркет",
    mapsQuery: "Tops Market Bangkok",
    aliases: ["Tops", "Топс"],
  },
  {
    term: "Big C",
    canonical: "Big C Supercenter",
    type: "store",
    category_ru: "Гипермаркет",
    mapsQuery: "Big C Supercenter Bangkok",
    aliases: ["Биг Си"],
  },
  {
    term: "Makro",
    canonical: "Makro Wholesale",
    type: "store",
    category_ru: "Оптовый магазин",
    mapsQuery: "Makro Bangkok",
    aliases: ["Макро"],
  },
  {
    term: "Lotus's",
    canonical: "Lotus's (formerly Tesco Lotus)",
    type: "store",
    category_ru: "Гипермаркет",
    mapsQuery: "Lotus's Thailand Bangkok",
    aliases: ["Tesco Lotus", "Lotus", "Лотус"],
  },
  {
    term: "Don Don Donki",
    canonical: "Don Don Donki (Japanese superstore)",
    type: "store",
    category_ru: "Японский магазин",
    mapsQuery: "Don Don Donki Bangkok",
  },
  {
    term: "Gourmet Market",
    canonical: "Gourmet Market",
    type: "store",
    category_ru: "Супермаркет",
    mapsQuery: "Gourmet Market Siam Paragon Bangkok",
    aliases: ["Гурме маркет"],
  },

  // ── Exchange Offices ───────────────────────────────────────────────────────
  {
    term: "SuperRich",
    canonical: "SuperRich Currency Exchange",
    type: "exchange",
    category_ru: "Обменник",
    mapsQuery: "SuperRich currency exchange Bangkok",
    aliases: ["Super Rich", "Супер Рич", "SuperRich 1965"],
  },
  {
    term: "Vasu Exchange",
    canonical: "Vasu Exchange (Sukhumvit Soi 7/1)",
    type: "exchange",
    category_ru: "Обменник",
    mapsQuery: "Vasu Exchange Bangkok Sukhumvit",
    aliases: ["Vasu"],
  },
  {
    term: "Happy Rich",
    canonical: "Happy Rich Currency Exchange (Don Mueang Airport)",
    type: "exchange",
    category_ru: "Обменник",
    mapsQuery: "Happy Rich exchange Don Mueang Airport Bangkok",
  },
  {
    term: "X-One",
    canonical: "X-One Exchange (Surawong)",
    type: "exchange",
    category_ru: "Обменник",
    mapsQuery: "X-One exchange Surawong Bangkok",
  },

  // ── Transport Terminals ────────────────────────────────────────────────────
  {
    term: "Ekkamai Bus Terminal",
    canonical: "Ekkamai Bus Terminal (Eastern Bus Terminal)",
    type: "terminal",
    category_ru: "Автовокзал",
    mapsQuery: "Ekkamai Bus Terminal Bangkok",
    aliases: ["Eastern Bus Terminal"],
  },
  {
    term: "Mo Chit Bus Terminal",
    canonical: "Mo Chit 2 Bus Terminal (Northern Bus Terminal)",
    type: "terminal",
    category_ru: "Автовокзал",
    mapsQuery: "Mo Chit 2 Bus Terminal Bangkok",
    aliases: ["Northern Bus Terminal"],
  },
  {
    term: "Southern Bus Terminal",
    canonical: "Southern Bus Terminal (Sai Tai Mai, Taling Chan)",
    type: "terminal",
    category_ru: "Автовокзал",
    mapsQuery: "Southern Bus Terminal Sai Tai Mai Bangkok",
    aliases: ["Sai Tai Mai", "Taling Chan Bus Terminal"],
  },
  {
    term: "Hua Lamphong",
    canonical: "Hua Lamphong Railway Station",
    type: "terminal",
    category_ru: "Ж/д вокзал",
    mapsQuery: "Hua Lamphong Railway Station Bangkok",
    aliases: ["Хуа Лампонг"],
  },

  // ── Immigration Offices ────────────────────────────────────────────────────
  {
    term: "Chaeng Wattana",
    canonical: "Chaeng Wattana Government Complex (Immigration Division 1)",
    type: "immigration",
    category_ru: "Иммиграционный офис",
    mapsQuery: "Chaeng Wattana Government Complex Immigration Bangkok",
    aliases: ["Чаенгваттана", "Чанвата", "Chaeng Wattana Government Complex"],
  },
  {
    term: "IT Square Lak Si",
    canonical: "IT Square Lak Si (Immigration Office)",
    type: "immigration",
    category_ru: "Иммиграционный офис",
    mapsQuery: "IT Square Lak Si Immigration Bangkok",
    aliases: ["IT Square", "Лакси"],
  },
  {
    term: "Samut Prakan immigration",
    canonical: "Samut Prakan Immigration Office",
    type: "immigration",
    category_ru: "Иммиграционный офис",
    mapsQuery: "Samut Prakan Immigration Office Thailand",
    aliases: ["Samut Prakan"],
  },

  // ── Consulates / Embassies ────────────────────────────────────────────────
  {
    term: "Russian Embassy Bangkok",
    canonical: "Embassy of Russia in Bangkok",
    type: "consulate",
    category_ru: "Посольство",
    mapsQuery: "Russian Embassy Bangkok Thailand",
    aliases: ["консульство РФ", "Посольство России"],
  },
  {
    term: "Russian Embassy in Laos",
    canonical: "Embassy of Russia in Vientiane, Laos",
    type: "consulate",
    category_ru: "Посольство",
    mapsQuery: "Russian Embassy Vientiane Laos",
    aliases: ["российское посольство Вьентьян"],
  },

  // ── Tourist Attractions ────────────────────────────────────────────────────
  {
    term: "Grand Palace",
    canonical: "Grand Palace & Wat Phra Kaew",
    type: "attraction",
    category_ru: "Достопримечательность",
    mapsQuery: "Grand Palace Bangkok",
    aliases: ["Королевский дворец", "Wat Phra Kaew"],
  },
  {
    term: "Wat Pho",
    canonical: "Wat Pho (Temple of the Reclining Buddha)",
    type: "attraction",
    category_ru: "Храм",
    mapsQuery: "Wat Pho Bangkok",
    aliases: ["Wat Po", "Ват По"],
  },
  {
    term: "Wat Arun",
    canonical: "Wat Arun (Temple of Dawn)",
    type: "attraction",
    category_ru: "Храм",
    mapsQuery: "Wat Arun Bangkok",
    aliases: ["Ват Арун"],
  },
  {
    term: "King Power Mahanakhon",
    canonical: "King Power Mahanakhon Skywalk",
    type: "attraction",
    category_ru: "Смотровая площадка",
    mapsQuery: "King Power Mahanakhon Skywalk Bangkok",
    aliases: ["Mahanakhon", "Mahanakhon SkyWalk", "Маханакхон"],
  },
  {
    term: "Lumphini Park",
    canonical: "Lumphini Park",
    type: "attraction",
    category_ru: "Парк",
    mapsQuery: "Lumphini Park Bangkok",
    aliases: ["Lumpini Park", "Люмпини"],
  },

  // ── Rooftop Bars & Restaurants ─────────────────────────────────────────────
  {
    term: "Tichuca",
    canonical: "Tichuca Rooftop Bar (T-One Building, Sukhumvit Soi 40)",
    type: "restaurant",
    category_ru: "Руфтоп-бар",
    mapsQuery: "Tichuca Rooftop Bar Bangkok Sukhumvit Soi 40",
    aliases: ["Тичука"],
  },
  {
    term: "Sky Bar Lebua",
    canonical: "Sky Bar at Lebua Hotel",
    type: "restaurant",
    category_ru: "Скайбар",
    mapsQuery: "Sky Bar Lebua Bangkok",
    aliases: ["Lebua Sky Bar", "Sky Bar"],
  },
  {
    term: "Vertigo",
    canonical: "Vertigo Rooftop Restaurant (Banyan Tree Bangkok)",
    type: "restaurant",
    category_ru: "Руфтоп-ресторан",
    mapsQuery: "Vertigo Rooftop Banyan Tree Bangkok",
    aliases: ["Vertigo Bar"],
  },
  {
    term: "Red Sky",
    canonical: "Red Sky Bar & Restaurant (Centara Grand at CentralWorld)",
    type: "restaurant",
    category_ru: "Руфтоп-бар",
    mapsQuery: "Red Sky Centara Grand CentralWorld Bangkok",
    aliases: ["Red Sky Restaurant"],
  },
  {
    term: "Brewski",
    canonical: "Brewski Rooftop Craft Beer Bar (Radisson Blu Plaza Bangkok)",
    type: "restaurant",
    category_ru: "Руфтоп-бар",
    mapsQuery: "Brewski Rooftop Bar Radisson Blu Bangkok",
    aliases: ["Брюски"],
  },
  {
    term: "River Vibe Bar",
    canonical: "River Vibe Bar",
    type: "restaurant",
    category_ru: "Руфтоп-бар",
    mapsQuery: "River Vibe Bar Bangkok",
    aliases: ["River Vibe"],
  },
  {
    term: "Breakfast Story",
    canonical: "Breakfast Story",
    type: "restaurant",
    category_ru: "Кафе",
    mapsQuery: "Breakfast Story Bangkok",
    aliases: ["Брекфаст Стори"],
  },
  {
    term: "Sarnies",
    canonical: "Sarnies Bangkok (Sukhumvit Soi 37)",
    type: "restaurant",
    category_ru: "Кафе",
    mapsQuery: "Sarnies Bangkok Sukhumvit",
  },
  {
    term: "Kub Kao Kub Pla",
    canonical: "Kub Kao Kub Pla Restaurant",
    type: "restaurant",
    category_ru: "Ресторан",
    mapsQuery: "Kub Kao Kub Pla Bangkok",
  },
  {
    term: "Samsara",
    canonical: "Samsara Restaurant Bangkok",
    type: "restaurant",
    category_ru: "Ресторан",
    mapsQuery: "Samsara restaurant Bangkok",
  },

  // ── Other cities / destinations ────────────────────────────────────────────
  {
    term: "Pattaya",
    canonical: "Pattaya",
    type: "city",
    category_ru: "Город / курорт",
    mapsQuery: "Pattaya Thailand",
    aliases: ["Паттайя"],
  },
  {
    term: "Phuket",
    canonical: "Phuket",
    type: "city",
    category_ru: "Остров / курорт",
    mapsQuery: "Phuket Thailand",
    aliases: ["Пхукет"],
  },
  {
    term: "Koh Samui",
    canonical: "Koh Samui",
    type: "city",
    category_ru: "Остров / курорт",
    mapsQuery: "Koh Samui Thailand",
    aliases: ["Ko Samui", "Самуи", "Ко Самуи"],
  },
  {
    term: "Chiang Mai",
    canonical: "Chiang Mai",
    type: "city",
    category_ru: "Город",
    mapsQuery: "Chiang Mai Thailand",
    aliases: ["Чиангмай", "Chiangmai"],
  },
  {
    term: "Hua Hin",
    canonical: "Hua Hin",
    type: "city",
    category_ru: "Курортный город",
    mapsQuery: "Hua Hin Thailand",
    aliases: ["Хуа Хин"],
  },
  {
    term: "Krabi",
    canonical: "Krabi",
    type: "city",
    category_ru: "Провинция / курорт",
    mapsQuery: "Krabi Thailand",
    aliases: ["Краби"],
  },
  {
    term: "Vientiane",
    canonical: "Vientiane, Laos",
    type: "city",
    category_ru: "Город (Лаос)",
    mapsQuery: "Vientiane Laos",
    aliases: ["Вьентьян"],
  },
  {
    term: "Phnom Penh",
    canonical: "Phnom Penh, Cambodia",
    type: "city",
    category_ru: "Город (Камбоджа)",
    mapsQuery: "Phnom Penh Cambodia",
    aliases: ["Пном Пень", "Пномпень"],
  },
  {
    term: "Ayutthaya",
    canonical: "Ayutthaya (ancient capital)",
    type: "city",
    category_ru: "Город / история",
    mapsQuery: "Ayutthaya Thailand",
    aliases: ["Аюттайя", "Ayudhaya"],
  },
  {
    term: "Si Racha",
    canonical: "Si Racha",
    type: "city",
    category_ru: "Город",
    mapsQuery: "Si Racha Chonburi Thailand",
    aliases: ["Sriracha", "Шри Рача"],
  },
];

export function mapsUrl(entry: LocationEntry): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
    entry.mapsQuery
  )}`;
}
